# Generated by Django 5.1.1 on 2024-09-10 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='activation',
            field=models.CharField(default='n/a', max_length=1000),
        ),
        migrations.AddField(
            model_name='operator',
            name='cancellation',
            field=models.CharField(default='n/a', max_length=1000),
        ),
        migrations.AddField(
            model_name='operator',
            name='check_usage',
            field=models.CharField(default='n/a', max_length=200),
        ),
        migrations.AddField(
            model_name='operator',
            name='replacement',
            field=models.CharField(default='n/a', max_length=1000),
        ),
        migrations.AddField(
            model_name='operator',
            name='topup_eligibility',
            field=models.CharField(default='n/a', max_length=500),
        ),
    ]
