# Generated by Django 5.1.1 on 2024-09-10 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0002_operator_activation_operator_cancellation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='kyc',
            field=models.CharField(default='n/a', max_length=500),
        ),
        migrations.AddField(
            model_name='operator',
            name='provider_name',
            field=models.CharField(default='n/a', max_length=124),
        ),
    ]
